a = int(input("Enter First No.: "))
b = int(input("Enter Second No.: "))
print("Enter 1 for Addition")
print("Enter 2 for Subtraction")
print("Enter 3 for Multiplication")
print("Enter 4 for Division")
print("Enter 5 for Modulus")
print("Enter 6 for Exponentiation")
print("Enter 7 for Floor Division")
c = int(input("Enter Your Choice:"))